name: J2 Syntax Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:         
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Jinja2 Syntax Check
      uses: cotsiosglad/Jinja2SyntaxChecker@v1.0.0
      with:
        directory: ./
